### PR TITLE
Viz js

### PR DESCRIPTION
**Pull request by npetzall**
Really big PR to add Viz.js based of #202

### CODE REVIEW

**Comment by npetzall** [comment]
Ran tests on my work computer. First it took only 1m24 seconds to run. Love my work computer. But I guess there are memory limitations on travis-ci that I need to check.

**Comment by npetzall** [comment]
Got error on my windows box, seems 1 GB memory is a problem. 

> totalMemory Option
>An additional, advanced option is provided for working with the Emscripten module instance.
>totalMemory <number> The total memory available for the Emscripten module instance. This should be a power of 2. The default of 16MB should be sufficient for most cases — only consider using a larger number if you run into the error "Cannot enlarge memory arrays".

So setting 64 MB.

**Comment by npetzall** [comment]
Will look into using viz.js 2.x when this has been merged.
Currently reinstalling windows in libvirt instead of virtualbox hoping that docker will work.

**Comment by npetzall** [comment]
On a side note, the memory option doesn't exist in 2.x.

@rafalkasa should i add the memory as a commandline argument and default to 64 MB.

**Comment by rafalkasa** [comment]
I think that 64 MB is not the problem in nova days. So please set it

**Comment by npetzall** [comment]
It's set to 64 MB currently. We can keep it at 64 MB until we get an error report.

So still need to update the docs and set 6.1.0-SNAPSHOT as version.

Docs can contain expected error related to 64 MB memory.

**Comment by npetzall** [comment]
@rafalkasa Have you had the time to test it. I've been struggeling to get a windows system with docker on it. So I have only run tests without docker. I'm gonna see if I can use a another computer at home as a remote docker host.

**Comment by rafalkasa** [comment]
@npetzall I will try to test today evening or tomorrow and let you know mine feedback

**Comment by npetzall** [comment]
I'll do some clean up I think I left a class that's not used anymore. Update version in pom, update docs and if this has minimal impact on 6.0 "flow" I'm gonna merge it.

**Comment by rafalkasa** [comment]
@npetzall each time when I try to run Schemaspy analysis using viz.js I received the error as below:
```
ERROR - Failed to generate Table diagram
org.schemaspy.output.diagram.DiagramException: Failed to generate Table diagram
	at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:67)
	at org.schemaspy.output.html.mustache.diagrams.MustacheDiagramFactory.generateTableDiagram(MustacheDiagramFactory.java:44)
	at org.schemaspy.output.html.mustache.diagrams.MustacheTableDiagramFactory.generateTableDiagrams(MustacheTableDiagramFactory.java:76)
	at org.schemaspy.SchemaAnalyzer.generateHtmlDoc(SchemaAnalyzer.java:420)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:256)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:119)
	at org.schemaspy.cli.SchemaSpyRunner.runAnalyzer(SchemaSpyRunner.java:97)
	at org.schemaspy.cli.SchemaSpyRunner.run(SchemaSpyRunner.java:86)
	at org.schemaspy.Main.main(Main.java:48)
Caused by: org.schemaspy.output.diagram.DiagramException: javax.script.ScriptException: Error: No or improper image file="../../images\primaryKeys.png"
 in <eval> at line number 94 at column number 4
	at org.schemaspy.output.diagram.vizjs.VizJSDot.generateDiagram(VizJSDot.java:72)
	at org.schemaspy.output.diagram.DiagramFactory.generateTableDiagram(DiagramFactory.java:64)
	... 8 common frames omitted
```

**Comment by npetzall** [comment]
I know what's wrong fix when I'm fixing the other stuff.

**Comment by npetzall** [comment]
The pointer thing is strange. Since I added css for pointer in schemaspy.css and since I'm using `<object>` it should be applied. I however only checked in Firefox and on Linux and it applied it. I'll doublecheck and make sure it works on windows and IE

**Comment by rafalkasa** [comment]
I tested a few times it doesn't this is a common Internet Exproler issue...

**Comment by rafalkasa** [comment]
@npetzall please let me know when you will have the new version

**Comment by npetzall** [comment]
Still have the IE cursor thing to fix.

**Comment by npetzall** [comment]
@rafalkasa I didn't see any problem in Edge. However I felt the move cursor weird so I removed it.
Also realized that the css that you linked I hadn't added it or it was removed in a rebase.

Could you give it another shot. If it's strange please supply IE / Edge version.

**Comment by rafalkasa** [comment]
I will test your changes at evening and let you know my feedback including IE

**Comment by npetzall** [comment]
I generated on Linux and opened thru shared folder to Edge and didn't see any problems.

**Comment by rafalkasa** [comment]
@npetzall everything is working! So if you don't have anything against.
I'm ready to merge changes to the master branch 😄 

Tested in Chrome, IE, Edge and Firefox cursor pointer appear everywhere

**Comment by npetzall** [comment]
Go for it, I'll handle any build issue in an hour or two. Did you check the docs?

**Comment by rafalkasa** [comment]
Before merge we should know that drag and move diagrams stop working, for all webbrowsers when you remove `style="cursor: move;"`

http://schemaspy.org/sample/relationships.html try to click in diagram catch and move.
In the same time this style is ovverrading somehow 'cursor: pointer' in IE and Edge for the rest webbrowsers eveyrthing is working correctly. 

When I added graphviz.css to the DotNode this give possibility to drag and move diagrams and cursor pointer appear correctly for diagrams.

**Comment by npetzall** [comment]
Hold of the merge then. Do you know which js library contained this feature?

**Comment by rafalkasa** [comment]
Nice documentation 😄

**Comment by rafalkasa** [comment]
Because this issue with `cursor:move` exist only for IE so maybe we will create two CSS files:
- ie-only.css
- not-ie.css
and add in the template layout we will include
```
<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="ie-only.css" />
<![endif]-->
<!--[if !IE]><!-->
	<link rel="stylesheet" type="text/css" href="not-ie.css" />
 <!--<![endif]-->
```
in `not-ie.css` file we will have class with `cursor:move` and in `ie-only.css `file this class will not exist.

**Comment by rafalkasa** [comment]
I try to find the better solution but this error with missing `cursor:pointer `exists in the current SchemSpy version for IE. I believe that our users do not use IE too much 😄

**Comment by rafalkasa** [comment]
@npetzall, @igor-suhorukov awesome contribution, after fixes and tests I'm ready to merge

**Comment by rafalkasa** [comment]
congratulations 👍

**Pull request merged**
