### PR TITLE
Removed dependency to Mustache in DotNode

### PR DESCRIPTION
**Pull request by npetzall**
* Reduced complexity and duplication
* Later we might want to do this a lot cleaner

### CODE REVIEW

**Comment by rafalkasa** [comment]
Hi @npetzall for me the changes look good. 
Please consider using mustache to manage the DotNode templates in the same way as we have done with .html layout.

We will have xml files with DotNode layout and files will be generated by mustache engine. 
@npetzall what do you think about?

**Comment by npetzall** [comment]
I've looked at a dot-lang library earlier.

The mustache thing would work. In reality it wouldn't be that horrible to have as a dependency for dot file generation. I'll think about it.

**Comment by npetzall** [comment]
I'm gonna ponder this for a while, I think #328 is interesting.

I need to take a closer look on the width thingy and see what can be done. Probably need to create some dto to feed into the template. It's an interesting approach.

**Comment by npetzall** [comment]
@rafalkasa you said i look ok. Can we add this and we can update change later.

**Comment by rafalkasa** [comment]
I have added the new issue about the possibility of use Mustache for **dot** files. #458

**Pull request merged**
