### PR TITLE
if database name is not provided xml filename is null

### PR DESCRIPTION
**Pull request by karlkauc**
fallback to dbmsMeta.getProductName
fallback to hard coded "UNKNOWN"

### CODE REVIEW

**Comment by npetzall** [comment]
Sadly we currently have the same logic for name duplicated in HtmlMainPage or something similar with a link to the xml file. Same logic needs to be applied there until we have figured out a good Output Result object to contain the computed filename.

**Comment by karlkauc** [comment]
I see.
What about extending the getName() in Database.java
```java
    public String getName() {
        if (Objects.nonNull(databaseName)) {
            return databaseName;
        }
        if (Objects.nonNull(dbmsMeta.getProductName())) {
            return dbmsMeta.getProductName();
        }
        return "UNKNOWN DATABASE NAME";
    }
```

**Comment by npetzall** [comment]
How would you feel about introducing a OutputResult class with a list of Links that is just a simple object with href and name.

This would allow us to move some other logic to individual classes as well, the insert delete order for instance.

**Comment by karlkauc** [comment]
Good idea. 

Database name could also be selected via the database metadata (enhancing the properties files). 

For Oracle this would be: 
```sql
select ora_database_name from dual;
```

For SQL92 compliant databases this would be: 
```sql
select SCHEMA_NAME from information_schema.schemata;
```

**Comment by npetzall** [comment]
I'll write some more later. But if we think of something good we could do bigger changes for 7.0

Currently db (called databaseName) is used from the commandline for certain dbms when connecting and moste sql overrides currently assumes a selection of default database/schema from connectionstring.

So having a user supplied databaseName and a dbms supplied might be confusing.

**Comment by npetzall** [comment]
So the problem is that database can be null, this is since `-db` is "required" but not enforced.
`-db` can be marked as required.

Looking over the database types we have. It's seems that they all have `<db>` in the connectionString.
From that point of view DB should be required. Since it's also required for xml and for html generation.

But removing `-db` has been mentioned #300 and skipping `-db` in connectionString causes #287 

But the usage could be removed. JDBC only gives catalog and schema. We could just remove the usage of Database.getName() and build the fileName with only getCatalog().getName() + "_" + getSchema.getName() + ".xml" (since Catalog is/should be the databaseName and schema i schema)

Then work could be continued on removing `-db` since I believe that SchemaSpy should have the behavior described in https://github.com/schemaspy/schemaspy/issues/329#issuecomment-391483518
when reading it remember catalog is database and schema is schema and we should ignore mysql until they have decided on how they wanna move forward in their jdbc-driver.

Instead of using user input in output we use dbms supplied data.

**Comment by npetzall** [comment]
Last commit could you move that to a new PR and reference issue #369 in the commit?

**Comment by npetzall** [comment]
Commit #301798 needs to be dropped from this PR.

And what do you say about changing file naming to [Catalog].[Schema].xml and also adding the OutputResults class?

**Comment by karlkauc** [comment]
Hi,
yes [Catalog].[Schema].xml is a good idea.
Thanks

**Comment by npetzall** [comment]
@karlkauc Will you do another PR or should I fixit after I've abstracted Graphviz?

**Comment by karlkauc** [comment]
I will do another PR - but not today. 

I would like to add some features I still miss to use it in my office. 
E.g. triggers, table size, materialized views, user-defined data types, partitioned tables, ...

I hope I can do some PR in the next few weeks.

**Comment by npetzall** [comment]
Could we create issue for these enhancements so that we can discuss implementations and also collaborate on solutions.

**Pull request closed without merging**
