### PR TITLE
added -template parameter.

### PR DESCRIPTION
**Pull request by ismailsimsek**
adds  -template parameter. if not provided uses "main/resources/layout/" by default

### CODE REVIEW

**Comment by rafalkasa** [comment]
Hi @ismailsimsek 

Thank you for your contribution. I will review your PR and merge with current version.
I have plan to release new SchemeSpy in this month, and finalise all work that I have been done.

**Comment by ismailsimsek** [comment]
updated conflict files, now its working with -template parameter.

**Comment by ismailsimsek** [comment]
Reopen.

**Comment by rafalkasa** [comment]
Hi @ismailsimsek 

I don't know what I'm doing incorrect that yours merged PR are not available as contribution.
I would like to see everything your work as contributor to the project.

Could you help some how ? Maybe can you crate small change and we will verify how we should creating PR to be present as contribution ?

Based on this I will prepare contribution documentation to the project.

Thank you in advance

**Pull request merged**
