### PR TITLE
Added the dynamic MaxTitleWidth into DotNode.java for Title

### PR DESCRIPTION
**Pull request by Kamyabnz**
Because of small columns and big titles, the titles would have gotten squished, i have added the same procedure to the Titles too. The issue was: #586

### CODE REVIEW

**Comment by Kamyabnz** [comment]
I found the problem, why we are getting this errors. The problem is with graphviz, that gives out the ERROR of the width being too small and so it tries to change it. But it still gives out errors so the build fails, I think we just have to check before that if graphviz is running or -vizjs has been choosen.

**Comment by Kamyabnz** [comment]
Yes it should have and also if you try the same code with graphviz it gives out for example this error:
```
ERROR - D:\graphviz-2.38-Mid\release\bin\dot -Tpng produkt.implied1degrees.dot -oprodukt.implied1degrees.png -Tcmapx: Warning: cell size too small for content
ERROR - D:\graphviz-2.38-Mid\release\bin\dot -Tpng produkt.implied1degrees.dot -oprodukt.implied1degrees.png -Tcmapx: in label of node produkt
```

But the result does not have any problems. With both vizjs and graphviz in my case atleast.

**Comment by npetzall** [comment]
Yeah should probably be a warning but we just read stderror so that's why it's classified as an error. I've seen the output before nothing new.

**Comment by Kamyabnz** [comment]
Yes it should actually be a warning because it also says i the message but well as you did say it is classified as an error.

**Comment by npetzall** [comment]
Did you recreate your fork or did I do something really horrible, like delete it  (which I shouldn't be able to). The branch for this PR is gone.

**Comment by npetzall** [comment]
Closed with #615

**Pull request closed without merging**
