### PR TITLE
fix maven warning

### PR DESCRIPTION
**Pull request by ismailsimsek**
replace ${version} with ${project.version}. solves maven warning

### CODE REVIEW

**Comment by rafalkasa** [comment]
Hi @ismailsimsek 

Could you merge this change with your master and create PR from your master branch or change this branch to default.
Please look at https://help.github.com/articles/i-don-t-see-myself-in-the-repository-contributors-graph/
https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

I would like test this merge issue where you are not visible as contributor. Thx

**Comment by ismailsimsek** [comment]
Thanks for the the link. 
looks like my commits were not matching following condition. updated my email adress. it shuld work correctly for next PR requests.  also updated this commit, now it shuld work. 

> The email address used for the commits is associated with your GitHub account.

**Comment by rafalkasa** [comment]
Hurry you are right now visible https://github.com/schemaspy/schemaspy/graphs/contributors

Happy New Year and thank you for your work here !!!
https://www.youtube.com/watch?v=iDicwfAhDaM

**Comment by ismailsimsek** [comment]
:) great thank you 
Happy New Year

**Pull request merged**
