### PR TITLE
Removed stereotype from all classes not tied to application

### PR DESCRIPTION
**Pull request by npetzall**
* Added new wiring configuration
* Left stereotypes in commandline classes

### CODE REVIEW

**Comment by rafalkasa** [comment]
@npetzall I would like to understand why Spring class with @Configuration is better than Spring stereotypes ? One of advantage is that Spring will not have to do Component scans when context start and second is that configuration is in Java class, but what are the other advantages ?

**Comment by npetzall** [comment]
Well the real idea behind it is that we encapsulate the usage of spring to the application and everything that we might be libraries doesnt have a dependency on spring. Since not everybody wants spring on their classpath.

There are ways around the having Spring as a dependency when using annotations, since annotations might not be used you could specify annotations as provided. I think, but I believe they will be needed during compile-time(believe).

So it's more of a structural thing. Having stereotypes all over the place which more or less resorts to autowire hell, instead of a readable config. Aka, config can be read prior to runtime, componentscan will be resolved during runtime. You'll never know what you'll get.

But as I said in the beginning, modules, libraries and #157

**Comment by rafalkasa** [comment]
Could you explain me how someone will be using the SchemaSpy as library but will not using the dependencies in code that Spring is resolving as IoC ? 

Maybe I don't understand what you invent, but I can imagine that some one is using SchemaSpy as library to use core SchemaSpy modules / functions for retrieve as a collection all tables from database with the details.

**Comment by npetzall** [comment]
I'll write a longer explanation later but this comment is pretty on point. https://github.com/schemaspy/schemaspy/issues/157#issuecomment-335926877

**Comment by rafalkasa** [comment]
@npetzall before you will spend your time to write explanation form me please let me read the #157 comments

**Comment by npetzall** [comment]
A sort explanation would be that someone that wishes to use schemaspy or modules from schemaspy would wire them up themselves.

Including spring might cause problems even for people using spring. Since they might be using a different version. (They are pretty compatible, but they would need to dissect our jar to remove the spring code, unless we create multiple jars).

**Comment by rafalkasa** [comment]
@npetzall now I understand a little better the idea behind the changes and advantage that offer `@Configuration` classes. Thank you for explanation. I will merge your changes

**Pull request merged**
