### PR TITLE
Allow to run other commands in in container

### PR DESCRIPTION
**Pull request by abitrolly**
If the first argument passed to entrypoint doesn't start with dash, it is the command that needs to be executed.

Taken from the best practices on ENTRYPOINT
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#entrypoint

### CODE REVIEW

**Comment by npetzall** [comment]
Can you explain the need to run other commands in the container, so that I may better understand your needs. 

You can always make use of `- -entrypoint`

**Comment by abitrolly** [comment]
Troubleshoot problems with executing SchemaSpy. Getting files out, inspecting the contents etc. For example making this PR work. I used to how PostgreSQL like containers allow to do this.

**Comment by abitrolly** [comment]
I just found out that I was using a very old version of snapshot container with `/entrypoint.sh` and all this time I was trying to understand why the entrypoint was wrong.
```
podman inspect docker.io/schemaspy/schemaspy:snapshot
```

**Comment by abitrolly** [comment]
I tested that the script works.

**Comment by npetzall** [comment]
If it's used for troubleshooting `podman run --entrypoint=sh` should be used instead of building in support for arbitrary commands in the container.

**Comment by abitrolly** [comment]
Then why `postgres` doesn't follow this advice?

**Comment by npetzall** [comment]
What advice? The one that I gave specifically for SchemaSpy?

I'm not a maintainer/developer of postgres. But I'm gonna guess and extrapolate a lot from the documentation.

Postgres container contains both the dbms and the commandline client psql. Which means that it has more than 1 application that is targeted as such they must support both.

So you're more or less comparing two different scenarios. We don't need that support, they need it.

**Pull request closed without merging**
