### PR TITLE
971 doc database types

### PR DESCRIPTION
**Pull request by npetzall**
Add sphinx extension to read from included dbtypes and add to documentation

### CODE REVIEW

**Comment by npetzall** [comment]
Either you build it and check it, or we setup a session to go over it.
I'm not sure about the layout/placement so I need you input.

**Comment by jesperolsson-se** [comment]
Will review after #1003 is resolved

**Comment by npetzall** [comment]
Are you sure that 1003 isn't an issue with this PR?

**Comment by jesperolsson-se** [comment]
You're correct. My bad!

**Review by jesperolsson-se — CHANGES_REQUESTED** [review]
I'd say, let's put the database name and the argument next to each other. Optionally, put them in a table.

Also, update the README :wink:

**Comment by npetzall** [comment]
Should they still be in the same page or should it be its own page?

I wonder if they are sorted, might be a good thing to have it sorted.

**Comment by jesperolsson-se** [comment]
> Should they still be in the same page or should it be its own page?

Same page for now. If someone finds the current page, they will see a pretty long page that also contains niche information. I think it's quite unlikely that they would start looking for "included" somewhere else. In the future, however, I agree that its own page would be better.

> I wonder if they are sorted, might be a good thing to have it sorted.

Good suggestion, but it might be a bit complicated. I recommend getting this merged first and then look into sorting. For example, I think it's most natural to sort on the database name (not file name nor the CLI parameter), you need to consider "JTDS", "11 or later" and similar - maybe even rename some of them?

**Comment by npetzall** [comment]
I've added a dbms property to databaseType and reduced the description. I also changed the css for the table after our talk.

It now looks like
image

I'm gonna continue with `-dbhelp` since description is changed and dbms can be used for sorting.

**Comment by npetzall** [comment]
I've did some simple update to the `-dbhelp`
image

**Comment by npetzall** [comment]
All I have left is update the build instructions.

**Comment by npetzall** [comment]
I'll have it fixed tomorrow. ConfigIT broke, Config.dumpUsage needs an update to output gets properties().getProperty("dbms")

**Pull request closed without merging**
