### PR TITLE
Removed usage of fork and added a helper library

### PR DESCRIPTION
**Pull request by npetzall**
The helper library is currently hosted on my bintray but it's public so no worries, I was supposed to be synched to jcenter and I'm looking into getting it on maven central.

All drivers located in ext-lib will be added to classpath for tests in verify phase.

### CODE REVIEW

**Comment by npetzall** [comment]
Now available on Jcenter will switch to Jcenter.

**Comment by npetzall** [comment]
Available in maven central will update

**Comment by rafalkasa** [comment]
Excellent work I'm still quite busy but I'm impressed about your work @npetzall

**Comment by rafalkasa** [comment]
@npetzall please resolve the conflicts

**Pull request merged**
