### PR TITLE
chore(FileNameGenerator): as decorator

### PR DESCRIPTION
**Pull request by npetzall**
* introducing NameOf as a String adapter
* fix sonarlint issues

### CODE REVIEW

**Comment by npetzall** [comment]
@jesperolsson-se Should we rename `FileNameGenerator` to `SafeFileName` or `SanatizedFileName`

**Comment by npetzall** [comment]
@jesperolsson-se just focus on the previous comment. I'll change the PR for review to be smaller.

**Comment by jesperolsson-se** [comment]
> @jesperolsson-se Should we rename `FileNameGenerator` to `SafeFileName` or `SanatizedFileName`

`SanatizedFileName` sounds good to me.

**Comment by npetzall** [comment]
Good, fix that as a separate PR.

**Pull request closed without merging**
