### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by jesperolsson-se**

### CODE REVIEW

**Comment by npetzall** [comment]
I would like to have the name connected to the processing. It would be interesting to see a spike if it's possible and which approach to name would work best.

I.e. The current name building would be instruction on how to build the graph and I would be able to build and get the name which would more or less just be a description of the instructions used. 

Within that name might need to change and that would be totally fine.

**Comment by jesperolsson-se** [comment]
Is this blocking the PR? To me, this sounds like suggestions for future improvements. I find that changes are much smoother when not trying to refactor and change behaviour at the same time.

**Comment by npetzall** [comment]
To be honest, I think you're playing it to safe.
This change is not needed, the idea is to have it removed. The name of the diagram has no true meaning.
It could be a guid as long as it's used in the correct place.(pointer/coordinates)
(uniqueness is the only requirement from the applications point of view, bad if files are overwritten).

Since the application currently doesn't care about the contents of the name, why are we?

That being said. The descriptive name is really important in troubleshooting. Sadly we do some troubleshooting.

**Comment by jesperolsson-se** [comment]
This change was asked for in #842. If you wish to change or remove the `Name` functionality, please create such a ticket. Discussing this in PR comments is off-topic and benefits no one.

Unless there are any problems here and now with my code changes, please approve and merge this PR.

**Comment by npetzall** [comment]
Wasn't clear that it was related to that issue. 

The concatenation was suggested early in the issue, removal was also suggested but later. If DefaultName was removed would the concatenation still be needed? Seems like Implied becomes a natural leaf.

**Comment by jesperolsson-se** [comment]
Discounting `DefaultName`, we still have three leaves: `Degree`, `Implied` and `Sized`. So `Concatenation` would still be needed, yes.

**Comment by npetzall** [comment]
```java
final Name name = new Concatenation(
  new Sized(compact),
  new Implied(includeImplied),
);
```
vs.
```java
final Name name = new Sized(
  compact,
  new Implied(includeImplied)
);
```

```java
final Name name = new Concatenation(
  new Degree(twoDegreesOfSeparation),
  new Implied(includeImplied)
);
```
vs.
```java
final Name name = new Degree(
  twoDegreesOfSeparation,
  new Implied(includeImplied)
);
```

**Comment by jesperolsson-se** [comment]
With these suggestions, value and arrangement would be intermixed. That makes each object more complex. Unnecessarily so, unless you see some benefit other than having one class fewer. (Which itself, I would argue pretty strongly, is a drawback.)

**Comment by npetzall** [comment]
So after discussions I'm getting ahead of myself. For Name composition is a better solution since there is no added functionality,
Decorator would possibly be a better pattern for building the an interactive graph. BUT, we aren't building a interactive graph yet.

**Pull request merged**
