### PR TITLE
Adding informix index test

### PR DESCRIPTION
**Pull request by npetzall**
* Added testcontainer for informix
* Added a assumption rule for driverClass that is quicker than
  testcontainer-junit.
* Added ignore to /database/@type for XML comparison.

### CODE REVIEW

**Comment by rafalkasa** [comment]
@npetzall if the assumption rule for driverClass is faster than testcontainer-junit maybe it will be good to add this also for added last time MSSQLServerIT ? So you have to merge first wit master branch.

**Comment by npetzall** [comment]
Not needed for mssql or mysql since drivers are defined in pom and available in maven.

**Comment by rafalkasa** [comment]
ok so I will merge your changes

**Comment by rafalkasa** [comment]
Super this is a big difference, congratulations

**Pull request merged**
