### PR TITLE
157 isolating spring to app

### PR DESCRIPTION
**Pull request by npetzall**
Moving CLI/App to own package.
This is a step in making CLI/App it's own module and isolating spring and cli from currently everything else.

### CODE REVIEW

**Comment by rafalkasa** [comment]
@npetzall your PR has conflicts that must be resolved

**Comment by npetzall** [comment]
I'll fix the debug option tonight, it's a small thing.
If it would be easier I can split this in to smaller pull requests.

**Comment by rafalkasa** [comment]
@npetzall maybe it will be better to split this PR because current PR is changing 67 clases. I can reviewed your change but I prefer to not change everything at once.

**Comment by npetzall** [comment]
I'll split and close this when done.

**Comment by npetzall** [comment]
Replaced with
#234 
#235 
#236 
#237 

Will do moving/relocation PR when above has been merged.
#234 should be merged first.

**Pull request closed without merging**
