### PR TITLE
Added data in columns page thru json object, deferedRender

### LINKED ISSUE #162: show columns page by page and not all at once
in the tables overview there's a control to scroll tables page by page:
grafik

We have database schemas that have about 12k columns across about 850 tables and views.
The columns.html hast just about 3mb in size but rendering of all columns in the schema in the browser at once takes some time.

So a control like that in the tables overview maybe could prevent the browser to render everything at once and make a click on the COLUMNS module more responsive.

### PR DESCRIPTION
**Pull request by npetzall**
* Removed Indexed columns from MustashTableColumn since set/list not
  needed

Small test and it seems it will be lot faster on large amount of columns, and a tiny bit slower on small amount of columns.

Fixes #162

### CODE REVIEW

**Comment by rafalkasa** [comment]
This looks very interesting I have to verify your PR on my current database. Nice work :-)

**Comment by mapausch** [comment]
Please correct me if I'm wrong: this is not yet available in SchemaSpy 6.0 or schemaspy@latest?
Couldn't spend any efforts to have a closer look on this in the last weeks, but in the next weeks I will have chance to test this on a database schema with about 12k columns.
So if this will be available in a nightly (or something similar) in the next time I could test.

**Comment by npetzall** [comment]
@mapausch Not yet but I ran a build on jitpack.io
https://jitpack.io/com/github/npetzall/schemaspy/162_pagination_perfomance-v6.0.0-rc1-gfd99a96-509/schemaspy-162_pagination_perfomance-v6.0.0-rc1-gfd99a96-509.jar

**Comment by npetzall** [comment]
Hot new version: https://jitpack.io/com/github/npetzall/schemaspy/162_pagination_perfomance-v6.0.0-rc1-gba5d6af-553/schemaspy-162_pagination_perfomance-v6.0.0-rc1-gba5d6af-553.jar

**Comment by npetzall** [comment]
@rafalkasa @mapausch have you had time to test this yet?

**Comment by rafalkasa** [comment]
I'm after tests for the database with a lot of columns the new solution is from 8 to 10 times faster.  For the database with a smaller amount of columns for me, the render results are pretty the same! 😄 

Excellent Work! @npetzall

**Comment by mapausch** [comment]
Sorry for my very late reply. But I think it's never too late to compliment :-)
First page now gets rendered in almost no time. Much faster than I ever could dream of.

Great Job. Thanks for your efforts.

**Pull request merged**
