### PR TITLE
Fixed reading from springboot jar.

### PR DESCRIPTION
**Pull request by npetzall**
ERROR - null
java.nio.file.FileSystemNotFoundException: null
	at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171)
	at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157)
	at java.nio.file.Paths.get(Paths.java:143)
	at org.schemaspy.db.config.PropertiesFinder.findClassPath(PropertiesFinder.java:61)
	at org.schemaspy.db.config.PropertiesFinder.find(PropertiesFinder.java:33)
	at org.schemaspy.db.config.PropertiesResolver.getDbProperties(PropertiesResolver.java:41)
	at org.schemaspy.Config.getDbProperties(Config.java:1348)
	at org.schemaspy.service.SqlService.connect(SqlService.java:46)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:178)
	at org.schemaspy.SchemaAnalyzer.analyze(SchemaAnalyzer.java:97)
	at org.schemaspy.Main.runAnalyzer(Main.java:80)
	at org.schemaspy.Main.run(Main.java:73)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716)
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at org.schemaspy.Main.main(Main.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)

When running the jar-file.

### CODE REVIEW

**Comment by npetzall** [comment]
I think this should be really important, got error on windows and linux and was unable to use schemaspy.

I'll see if I can add a test later on.

**Comment by npetzall** [comment]
How master isn't red/failed I can not understand....

**Comment by npetzall** [comment]
I know why, integration tests doesn't use the built jar but the classes dir. So test won't fail, neither will running from IDE but running the jar will fail.

Build would have failed when build_info had been merged but this commit is now included in that branch. 

@rafalkasa

**Comment by npetzall** [comment]
@rafalkasa I tried running the docker image and it failes with the above exception.
master branch i broken, snapshot is broken.

**Comment by rafalkasa** [comment]
@npetzall I try to test and verify each branch before the merge do you know which PR create the problem ?
Do you are sure that when I merge this PR issue will be resolved ?

**Comment by rafalkasa** [comment]
Maybe to avoid such situation in the future is possible to create the integration test in which we will use the  schemaspy.jar file. What do you think ?

**Comment by npetzall** [comment]
Problem was introduced with PR #230
Test doesn't failed since failsafe used classes dir instead of produced jar. 

This will fix the issue on Linux and windows.

**Comment by npetzall** [comment]
PR #238 includes a change in pom.xml that causes failsafe(maven plug in for integrationtesting) to use built jar instead of classes dir.

**Comment by npetzall** [comment]
@rafalkasa Close this and use #266 since it contains "enabling using built jar" and the evolution with this fix, so enabling = fails, this fix = ok.

**Comment by rafalkasa** [comment]
I'm a little confused should I merge this PR or close ?

**Pull request closed without merging**
