### PR TITLE
FAQ - Markdown: use [xyz] to create links to other objects

### PR DESCRIPTION
**Pull request by aisbergde**

### CODE REVIEW

**Comment by aisbergde** [comment]
I see that non of my documentation pull requests will be merged. Maybe there is no interest to contribute to the documentation?

**Comment by npetzall** [comment]
Sorry I missed that this was a pull request.

**Comment by aisbergde** [comment]
yes, regarding schema it doesn't work. remove this part when you merge

**Comment by npetzall** [comment]
I finally got some time to put on SchemaSpy.

I checked the code and it seems it only works with tables and views.

It could be refactored to work with routines and also with foreign schemas. Should probably be a separate issue/PR.

**Pull request merged**
